export const categoryTranslations = {
    "Restaurants": "Restaurants",
    "Shopping": "Shopping",
    "Vie Nocturne": "Nightlife",
    "Sport & Loisirs": "Sport & Leisure Activities",
    "Salons de beauté & Spas": "Beauty Salons & Spas",
    "Automobile": "Automobile",
    "Maisons & Travaux": "Houses & Works",
    "Cafés & Thés": "Coffees & Teas",
    "Fournitures d'énergie": "Power Supplies",
    "Art & Loisirs": "Art & Leisure",
    "Santé & Médical": "Health & Medical",
    "Services Professionnels": "Services For Professional",
    "Animaux": "Pets",
    "Immobilier": "Real Estate",
    "Hôtels & séjours": "Hotels & Stays",
    "Services Locaux": "Local Services",
    "Organisation d'Événements": "Event Organization",
    "Services Publics & Gouvernement": "Public Services & Government",
    "Services Financiers": "Financial Services",
    "Formation & Enseignement": "Training & Teaching",
    "Organisations Religieuses": "Religious Organization",
    "Voyage": "Travel",
    "Médias": "Media"
  }